### ISSUE TITLE
[Bug]: Long prompts throw an error with anthropic adapter

### ISSUE THREAD

**Issue by GordianDziwis** [olimorris/codecompanion.nvim#427] opened 2024-11-13 16:12 UTC
### Your `minimal.lua` config

```lua
---@diagnostic disable: missing-fields

--NOTE: Set config path to enable the copilot adapter to work.
--It will search the follwoing paths for the for copilot token:
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/hosts.json"
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/apps.json"
vim.env["CODECOMPANION_TOKEN_PATH"] = vim.fn.expand("~/.config")

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

-- Your CodeCompanion setup
local plugins = {
  {
    "olimorris/codecompanion.nvim",
    dependencies = {
      { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
      { "nvim-lua/plenary.nvim" },
      { "hrsh7th/nvim-cmp" },
      { "stevearc/dressing.nvim",          opts = {} },
      { "nvim-telescope/telescope.nvim" },
    },
    opts = {
      adapters = {
        anthropic = function()
          return require("codecompanion.adapters").extend("anthropic", {
            env = {
              api_key =
""
            },
            schema = {
              max_tokens = {
                default = 8192
              }
            }
          })
        end,
      },
      --Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
      strategies = {
        --NOTE: Change the adapter as required
        chat = { adapter = "anthropic" },
        inline = { adapter = "anthropic" },
      },
      opts = {
        log_level = "DEBUG",
      },
    },
  },
}

require("lazy.minit").repro({ spec = plugins })

-- Setup Tree-sitter
local ts_status, treesitter = pcall(require, "nvim-treesitter.configs")
if ts_status then
  treesitter.setup({
    ensure_installed = { "lua", "markdown", "markdown_inline", "yaml" },
    highlight = { enable = true },
  })
end

-- Setup completion
local cmp_status, cmp = pcall(require, "cmp")
if cmp_status then
  cmp.setup({
    mapping = cmp.mapping.preset.insert({
      ["<C-b>"] = cmp.mapping.scroll_docs(-4),
      ["<C-f>"] = cmp.mapping.scroll_docs(4),
      ["<C-Space>"] = cmp.mapping.complete(),
      ["<C-e>"] = cmp.mapping.abort(),
      ["<CR>"] = cmp.mapping.confirm({ select = true }),
      -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    }),
  })
end
```

### Error messages

  args = { "-sSL", "-D", "/run/user/1000/plenary_curl_69104fb2.headers", "--compressed", "-X", "POST", "-H", "Anthropic-Version: 2023-06-01", "-H", "X-Api-Key: "", "-H", "Anthropic-Beta: prompt-caching-2024-07-31", "-H", "Content-Type: application/json", "--data-raw", "{\"model\":\"claude-3-5-sonnet-20241022\",\"temperature\":0,\"system\":[{\"cache_control\":{\"type\":\"ephemeral\"},\"type\":\"text\",\"text\":\"You are an AI programming assistant named \\\"CodeCompanion\\\".\\nYou are currently plugged in to the Neovim text editor on a user's machine.\\n\\nYour core tasks include:\\n- Answering general programming questions.\\n- Explaining how the code in a Neovim buffer works.\\n- Reviewing the selected code in a Neovim buffer.\\n- Generating unit tests for the selected code.\\n- Proposing fixes for problems in the selected code.\\n- Scaffolding code for a new workspace.\\n- Finding relevant code to the user's query.\\n- Proposing fixes for test failures.\\n- Answering questions about Neovim.\\n- Running tools.\\n\\nYou must:\\n- Follow the user's requirements carefully and to the letter.\\n- Keep your answers short and impersonal, especially if the user responds with context outside of your tasks.\\n- Minimize other prose.\\n- Use Markdown formatting in your answers.\\n- Include the programming language name at the start of the Markdown code blocks.\\n- Avoid line numbers in code blocks.\\n- Avoid wrapping the whole response in triple backticks.\\n- Only return code that's relevant to the task at hand. You may not need to return all of the code that the user has shared.\\n- Use actual line breaks instead of '\\\\n' in your response to begin new lines.\\n- Use '\\\\n' only when you want a literal backslash followed by a character 'n'.\\n- All non-code responses must use English.\\n\\nWhen given a task:\\n1. Think step-by-step and describe your plan for what to build in pseudocode, written out in great detail, unless asked not to do so.\\n2. Output the code in a single code block, being careful to only return relevant code.\\n3. You should always generate short suggestions for the next user turns that are relevant to the conversation.\\n4. You can only give one reply for each conversation turn.\"}],\"messages\":[{\"content\":\"put =repeat(repeat('a', 80) . '\\\\n', 4000)\\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\\\\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\\\\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\\\\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\\\\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\\\\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\\\\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\\\\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

### Log output

```txt
Messages:
{ {
    content = "You are an AI programming assistant named \"CodeCompanion\".\nYou are currently plugged in to the Neovim text editor on a user's machine.\n\nYour core tasks include:\n- Answering general programming questions.\n- Explaining how the code in a Neovim buffer works.\n- Reviewing the selected code in a Neovim buffer.\n- Generating unit tests for the selected code.\n- Proposing fixes for problems in the selected code.\n- Scaffolding code for a new workspace.\n- Finding relevant code to the user's query.\n- Proposing fixes for test failures.\n- Answering questions about Neovim.\n- Running tools.\n\nYou must:\n- Follow the user's requirements carefully and to the letter.\n- Keep your answers short and impersonal, especially if the user responds with context outside of your tasks.\n- Minimize other prose.\n- Use Markdown formatting in your answers.\n- Include the programming language name at the start of the Markdown code blocks.\n- Avoid line numbers in code blocks.\n- Avoid wrapping the whole response in triple backticks.\n- Only return code that's relevant to the task at hand. You may not need to return all of the code that the user has shared.\n- Use actual line breaks instead of '' in your response to begin new lines.\n- Use '' only when you want a literal backslash followed by a character 'n'.\n- All non-code responses must use English.\n\nWhen given a task:\n1. Think step-by-step and describe your plan for what to build in pseudocode, written out in great detail, unless asked not to do so.\n2. Output the code in a single code block, being careful to only return relevant code.\n3. You should always generate short suggestions for the next user turns that are relevant to the conversation.\n4. You can only give one reply for each conversation turn.",
    id = 1947269257,
    opts = {
      visible = false
    },
    role = "system"
  }, {
    content = "aaaa...",
    id = 2034632946,
    opts = {
      visible = true
    },
    role = "user"
  }, {
    content = "aaa...",
    id = 2034632946,
    opts = {
      visible = true
    },
    role = "user"
  } }
[INFO] 2024-11-13 17:01:52
Chat request started
```
### Health check output

```
==============================================================================
codecompanion:                         require("codecompanion.health").check()

- Neovim version: 0.11.0
- Log file: /home/beavis/.repro/state/nvim/codecompanion.log

Plugins: ~
- OK plenary.nvim installed
- OK nvim-treesitter installed
- OK nvim-cmp installed
- OK telescope.nvim installed
- OK dressing.nvim installed

Tree-sitter parsers: ~
- OK markdown parser installed
- OK yaml parser installed

Libraries: ~
- OK curl installed
```

### Describe the bug

1. `:CodeCompanionChat`
2. `put =repeat(repeat('a', 80) . '', 4000)\n`
3. `<cr>`

Now it should send the request without an error.

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by GordianDziwis** [comment] 2024-11-13 16:30
@olimorris you should make a note in the issue template: that the error message could leak api keys.

**Comment by olimorris** [comment] 2024-11-13 16:32
@GordianDziwis it's in there already

**Comment by olimorris** [comment] 2024-11-13 16:45
Can you debug this and share the exact error message? I've shared up to 30,000 tokens at a time with Anthropic and never had any issues before. If you can share the specific prompt that breaks it, that would be helpful.

**Comment by GordianDziwis** [comment] 2024-11-13 16:59
Check the bug description. Maybe the issue is that it is a long visible promot and not a slash command or #?

**Comment by GordianDziwis** [comment] 2024-11-13 17:01
Or can't you see the bug description, because the key was leaked?

**Comment by GitMurf** [comment] 2024-11-13 18:24
Ok glad to hear it isn't just me! I get the following plenary error on basically any buffer over 1,000 lines when trying to add `#buffer` to the prompt.

I am getting the plenary `failed to spawn process` error. cc @olimorris (I know you asked above for more info on the error).

![image](https://github.com/user-attachments/assets/acada34d-8124-415c-889f-01499c5483b4)

**Comment by GitMurf** [comment] 2024-11-13 18:43
Oh my apologies when I saw anthropic I just assumed it was talking about Claude in general. But now I see this is for the anthropic adapter. Mine is for Copilot adapter using claude. Still may be related, but wanted to call out my misunderstanding.

**Comment by GitMurf** [comment] 2024-11-13 18:53
> What operating system are you both on?

Windows 11

> How often has this occurred in the real world?

Not speaking to the "repeated a's" scenario, but my mentioned error I basically am getting when trying to include `#buffer` in any file more than 500 lines or so. So it is happening a lot.

> Are you on the latest plenary release?

I did the suggestion with using master. See what lazy.nvim shows below for my setup and commit it shows.

```lua
        url:    https://github.com/nvim-lua/plenary.nvim
        branch: master
        commit: 2d9b061
```

**Comment by GitMurf** [comment] 2024-11-13 19:14
As a "simple" test to make sure it kind of looks like regular code (not gigantic strings) and also no weird characters / symbols etc., I just repeated this until I started getting the error around 325 lines which is around 6,800 tokens according to an online token counter.

```lua
local dummy_foo_var = 'this is some dummy text and just trying to make the prompt longer a bit'
dummy_foo_var = 'this is some dummy text and just trying to make the prompt longer a bit'
dummy_foo_var = 'this is some dummy text and just trying to make the prompt longer a bit'
dummy_foo_var = 'this is some dummy text and just trying to make the prompt longer a bit'
dummy_foo_var = 'this is some dummy text and just trying to make the prompt longer a bit'
dummy_foo_var = 'this is some dummy text and just trying to make the prompt longer a bit'
```

The weird part is that it is a plenary error that keeps getting returned, not an error or rejection from the AI model api 🤔

**Comment by olimorris** [comment] 2024-11-13 19:50
I still can't recreate this. I'll try and do some more investigating over the weekend.

**Comment by olimorris** [comment] 2024-11-13 20:06
I'm on master but also on MacOS...wondering if Windows is potentially the cause. @GordianDziwis if you could confirm it isn't a Windows issue that would be be a nice thing to rule out...

**Comment by GitMurf** [comment] 2024-11-14 07:36
Ok @olimorris I bit the bullet and dove into plenary to get more info from the error because it was too long to show added detail other than the `failed to spawn process`.

- **Good news is**: It is NOT a Copilot / Claude context or api limit!
- **Bad news is**: It is what we expected with the data too big / long for plenary. But I think even more than that, it actually may be a `curl` issue (not super confident though).

The immediate thought I have is, how do we greatly reduce the amount of "crap" being sent in the headers. Half of the total length is likely spent on excessive damn escapes and `"` quotes everywhere given the JSON serialization! `\\`, `\"`, `\\n` etc.

So many escape characters! I wonder if there is a way we can sanitize / "scrub" around that to limit it?

![image](https://github.com/user-attachments/assets/49d1d0f2-aa3f-40da-9262-b0cc9d9a7c7a)

Without further ado... here is the error I mentioned: `ENAMETOOLONG: name too long`

![image](https://github.com/user-attachments/assets/d1f85c35-be44-4044-a794-2f3067388590)

**Comment by GitMurf** [comment] 2024-11-14 16:07
@olimorris your hunch was correct all along! Look here at `options.verbatim` on `uv.spawn` which is what plenary uses for curl.

https://github.com/luvit/luv/blob/master/docs.md#uvspawnpath-options-on_exit

Any idea how things could be stripped for Windows to try this verbatim option? 🤔

**Comment by olimorris** [comment] 2024-11-14 16:19
Not that I can think of. The [client/http](https://github.com/olimorris/codecompanion.nvim/blob/9ebaf79912a171b8fa8e3841144d067c29926316/lua/codecompanion/http.lua#L49) file is relatively simple and just utilises plenary.curl.

**Comment by olimorris** [comment] 2024-11-14 16:36
@GitMurf ... okay... this is interesting:

https://github.com/yetone/avante.nvim/pull/673

Looks like it's a known Windows issue and they got around it by writing to a temporary JSON file on disk.

Could you PR this? I don't have a Windows machine to test but I think we can pretty much copy https://github.com/yetone/avante.nvim/pull/673 exactly.

**Comment by olimorris** [comment] 2024-11-14 16:37
Infact...my http implementation might be a tad confusing so I can defo do this tonight.

**Comment by GitMurf** [comment] 2024-11-14 16:42
> Looks like it's a known Windows issue and they got around it by writing to a temporary JSON file on disk.

Oh awesome! I'm actually surprised my crazy googling adventure never stumbled upon this!

Also it looks like someone hit this a couple months ago but it went stale. The exact same error / experience I am hitting: https://github.com/yetone/avante.nvim/pull/622

**Comment by GitMurf** [comment] 2024-11-14 16:53
@olimorris I am a big fan of CC.nvim and trust their dev choices and just confirmed they also do the temp file concept :) so i feel good about that direction!

https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/canary/lua/CopilotChat/utils.lua#L48

**Comment by GitMurf** [comment] 2024-11-14 16:58
> Also strange that passing curl a JSON file of the body avoids the issue all together.

Yeah I thought it was strange too until I got to understanding what the initial janky windows problem is... the "name too long" error comes from the fact that windows cmd under the hood concatenates ALL of the plenary/spawn/curl args into a single gigantic string and append it to the command like a file path! This is why the error actually comes back on the PID because the process being spawned is basically a "file path" of the entire curl body 🤯🤦🏻‍♂️🤷🏻‍♂️

**Comment by GitMurf** [comment] 2024-11-14 17:01
> Infact...my http implementation might be a tad confusing so I can defo do this tonight.

@olimorris did you still want me to take a crack at a PR for this? Or are you now planning on tackling it? Thanks my friend!

**Comment by olimorris** [comment] 2024-11-14 17:03
I'll sort it out tonight and will tag you to test if that's cool?

**Comment by GitMurf** [comment] 2024-11-14 17:07
> until I started getting the error around 325 lines which is around 6,800 tokens

Its always nice to get validation that you aren't just completely crazy banging your head against the wall 🤣

![image](https://github.com/user-attachments/assets/3db42357-3a48-4f5e-9962-4bb0e7b52b12)

**Comment by GitMurf** [comment] 2024-11-14 17:09
> I'll sort it out tonight and will tag you to test if that's cool?

Yep. Sounds great! I'll have my eye out... I'm always working and living in GitHub anyways ;-)

**Comment by GitMurf** [comment] 2024-11-14 17:18
cc @olimorris just to speed up your search for tonight if you want/need to look at the api for plenary curl request with a filepath for the body: `<string | filepath | table>`

https://github.com/nvim-lua/plenary.nvim/blob/2d9b06177a975543726ce5c73fca176cedbffe9d/lua/plenary/curl.lua#L8

**Comment by GitMurf** [comment] 2024-11-14 18:13
Just hacked directly into plenary to send the request with a file instead of the string and went from error'ing out at about 7,000 tokens to not having a problem with 32,000+ tokens!! 🚀 

![image](https://github.com/user-attachments/assets/6178cae4-dc80-4573-a13a-b4f856b2ddc2)

**Comment by GordianDziwis** [comment] 2024-11-14 19:04
@olimorris I am on linux.

**Comment by GitMurf** [comment] 2024-11-14 19:33
@GordianDziwis checkout this thread (link below) I added some comments to. Do you have any emojis / icons / "non standard" utf characters in your applicable file(s) / prompts you are having issues with?

https://github.com/CopilotC-Nvim/CopilotChat.nvim/issues/464#issuecomment-2466901655

**Comment by olimorris** [comment] 2024-11-14 20:58
@GitMurf this should be fixed in the latest commit. Let me know your thoughts!

**Closed** 2024-11-14 20:58 UTC
Labels: bug

**Comment by olimorris** [comment] 2024-11-14 21:04
Also that Windows limit of 8,191 characters is almost as bad as Excel still not allowing two files with the same name to be open at once 😆

**Comment by GitMurf** [comment] 2024-11-14 22:43
> @GitMurf this should be fixed in the latest commit. Let me know your thoughts!

Will go try it right now!

**Comment by GitMurf** [comment] 2024-11-14 23:19
@olimorris the curl update to use the json file works like a charm! Just did a couple very large context tests and all is working wonderfully. Thanks for getting on it so fast! 🥳

**Comment by GitMurf** [comment] 2024-11-15 15:12
@GordianDziwis for what it's worth, someone else also confirmed the same issue on Linux and now resolved too: https://github.com/olimorris/codecompanion.nvim/discussions/420#discussioncomment-11263168

**Comment by olimorris** [comment] 2025-01-26 11:09
Hey @GordianDziwis just to let you know that the GitHub Secret Scanning tool alerted me to an API key being leaked in this issue. Just wanted to give you the heads up

**Comment by GordianDziwis** [comment] 2025-01-26 13:41
@olimorris Thanks, already replaced it.
