### ISSUE TITLE
[Bug]: TITLE DESCRIBING THE ISSUE

### ISSUE THREAD

**Issue by acsezen** [olimorris/codecompanion.nvim#549] opened 2024-12-18 09:37 UTC
### Your `minimal.lua` config

---

### Log output

---

### Health check output

```txt

==============================================================================
codecompanion: require("codecompanion.health").check()

- Neovim version: 0.10.2
- Log file: /home/xxx/.local/state/nvim/codecompanion.log

Plugins: ~
- OK plenary.nvim installed
- OK nvim-treesitter installed

Tree-sitter parsers: ~
- OK markdown parser installed
- OK yaml parser installed

Libraries: ~
- OK curl installed
```

#### Environment Details:
- **Plugin:** `codecompanion.nvim`
- **Dependency:** `blink.cmp`
- **Neovim Version: 0.10.2
- **Lazy.nvim Setup: Yes
- **Configuration:** Completion > Documentation > Auto_Show set to `true`

#### Observed Behavior:
The following error is thrown:

```
10:23:20 AM msg_showcmd i
 驪  Error  10:23:35 AM notify.error ...re/nvim/lazy/blink.cmp/lua/blink/cmp/lib/window/docs.lua:240: attempt to index local 'text' (a nil value)
```

#### Workaround:
Setting `completion.documentation.auto_show` to `false` in `blink.cmp` configuration prevents the error.

#### Expected Behavior:
No error should be thrown when using `@anyTools` in the chat buffer, even when `documentation.auto_show` is enabled.

#### Additional Information:
- **Reproducibility:** Happens consistently when the feature is enabled.
- **Potential Cause:** It appears that the `text` variable in `docs.lua` (line 240) is `nil`, which may indicate that the plugin isn't handling empty or missing documentation data correctly.

#### Steps to Reproduce:
1. Enable `completion.documentation.auto_show` in `blink.cmp` configuration.
2. Open the chat buffer with LL+a.
3. Use `@anyTools`.

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment] 2024-12-18 09:53
I can't reproduce this without a minimal.lua file so closing this. Please reopen with a title and follow the bug report guidelines.

**Closed by olimorris** 2024-12-18 09:53 UTC
Labels: bug
